apiVersion: v1
kind: ConfigMap
metadata:
  name: awesome-demo-api-info
  namespace: default
data:
  app-name: "awesome-demo-api"
  api-endpoint: "http://awesome-demo-api-api.default.svc.cluster.local"
  database-host: "awesome-demo-api-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://awesome-demo-api.local.gd"
