apiVersion: v1
kind: ConfigMap
metadata:
  name: test-stack-api-info
  namespace: default
data:
  app-name: "test-stack-api"
  api-endpoint: "http://test-stack-api-api.default.svc.cluster.local"
  database-host: "test-stack-api-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://test-stack-api.local.gd"
