apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-info
  namespace: default
data:
  app-name: "demo-app"
  api-endpoint: "http://demo-app-api.default.svc.cluster.local"
  database-host: "demo-app-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://demo-app.local.gd"
