apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-info
  namespace: default
data:
  app-name: "test-app"
  api-endpoint: "http://test-app-api.default.svc.cluster.local"
  database-host: "test-app-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://test-app.local.gd"
