apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todoer
  name: todoer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todoer
    spec:
      containers:
      - env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: todoerteam.todoerteam-todoerdb-postgresql.credentials.postgresql.acid.zalan.do
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: username
              name: todoerteam.todoerteam-todoerdb-postgresql.credentials.postgresql.acid.zalan.do
        - name: PGHOST
          value: todoerteam-todoerdb-postgresql.default.svc.cluster.local
        - name: DBNAME
          value: todoerdb
        image: syntasso/sample-todo-app:v1.0.0
        name: sample-todo-app
        resources: {}
status: {}
