apiVersion: v1
kind: ConfigMap
metadata:
  name: awesome-api-info
  namespace: default
data:
  app-name: "awesome-api"
  api-endpoint: "http://awesome-api-api.default.svc.cluster.local"
  database-host: "awesome-api-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://"
