apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: another-api-ingress
  namespace: default
  labels:
    app: another-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: another-api.local.gd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: another-api-api
                port:
                  number: 80
  tls:
    - hosts:
        - another-api.local.gd
      secretName: another-api-tls
