apiVersion: v1
kind: ConfigMap
metadata:
  name: another-api-info
  namespace: default
data:
  app-name: "another-api"
  api-endpoint: "http://another-api-api.default.svc.cluster.local"
  database-host: "another-api-postgres.default.svc.cluster.local"
  environment: "dev"
  ingress-url: "https://another-api.local.gd"
